export const eng = {
  type: "eng",
  jobs: {
    noItem: "No jobs",
    deleted: "Deleted!",
    workedWith: "people employed",
    headerText: "Job information",
    salary: "Salary:",
    numOfWorkers: "Number of employees:",
    phone: "Phone:",
    copy: "Copy",
    copied: "Copied!",
    time: "Time:",
    country: "Country:",
    region: "Region:",
    metro: "Subway:",
    address: "Address:",
    comment: "Commentary:",
    workers: "WORKERS",
    banned: "THE BANNED",
    deleteJob: "Delete",
    cancelJob: "Cancel",
    getJob: "Get the job",
    removeUser: "Remove",
    unbanUser: "Unban",
    modulTextDelete: "Do you want to delete this ad?",
    modulTextExit: "Do you want to cancel the job?",
    modulTextGet: "Do you want to get the job?",
    banErrorModulText: "The employer has banned you!",
    banErrorModulBtn: "Exit",
    unbanModul: "Do you want to unban the user?",
    modulRemoveBtn: "Remove",
    modulBanBtn: "Ban",
    modulCancelBtn: "Cancel",
  },
  homes: {
    noItem: "There are no ads for rent",
    deleteModul: "Do you want to delete this ad?",
    deleteBtn: "delete",
  },
  add: {
    addJobText: "Post a new job ad",
    addFree: "posting is absolutely free",
    addHomeText: "Post an ad to rent a house",
    myJobAdds: "My job ads",
    myHomeAdds: "My ads for rent",
  },
  addNewJob: {
    headerText: "Fill out the ad",
    jobName: "Enter job title...",
    numOfWorkers: "How many workers are needed?...",
    address: "Enter your working address...",
    comment: "Leave a comment about the job...",
    startingTime: "Start time",
    endingTime: "End time",
    country: "Country:",
    region: "Region:",
    countryDefault: "What country are you in?",
    regionDefault: "What region are you in?",
    line: "Line:",
    station: "Station:",
    saveBtn: "SAVE",
    errorModulBtn: "Exit",
    errorModulBtnJob: "View work",
    errorModulText: "You can only post 4 a day!",
    errorModulTextJob:
      "You already have a job! You must cancel the job to post!",
    jobNameError: "Enter a job title!",
    salaryError: "Enter the salary amount!",
    workersCountError: "Enter the number of employees!",
    workingPlaceError: "Enter a working address!",
    commentError: "Enter a comment!",
    startingTimeError: "Set the correct start time!",
    endingTimeError: "Set the correct end time!",
    regionError: "Enter Country and Region!",
    metroError: "Enter the subway close to work!",
    numberError: "Enter your phone number!",
  },
  addNewHome: {
    headerText: "Fill out the ad",
    rent: "Enter your monthly payment price...",
    address: "Enter your home address...",
    comment: "Leave a comment...",
    country: "Country:",
    region: "Region:",
    countryDefault: "What country are you in?",
    regionDefault: "What region are you in?",
    line: "Line:",
    station: "Station:",
    saveBtn: "SAVE",
    errorModulBtn: "Exit",
    errorModulText: "You can only post 4 a day!",
    imageError: "Please add a picture!",
    rentError: "Enter the monthly payment price!",
    addressError: "Enter the home address!",
    commentError: "Enter a comment!",
    regionError: "Enter Country and Region!",
    metroError: "Enter the subway close to home!",
    numberError: "Enter your phone number!",
  },
  chats: {
    noItem: "No messages",
    modulTextSelected: "Do you want to delete selected messages?",
    modulTextDelete: "Do you want to delete all messages?",
    modulTextBlock: "Do you want to block the user?",
    modulTextUnblock: "Do you want to unblock the user?",
    iconInfo: "Settings",
    chooseText: "select",
    deleteAllText: "delete all",
    unblockText: "unblock",
    blockText: "block",
    newMessagesText: "New messages",
  },
  profile: {
    phone: "Your phone number",
    gaveJobs: "people you employed",
    addedHomeAds: "houses for rent you have advertised",
    addedJobAds: "jobs you have added",
    takenJobs: "jobs you got",
    settings: "Settings",
    theme: "Dark Mode",
    jobsHistory: "Jobs History",
    homesHistory: "Home Rental History",
    changeLanguage: "Change Language",
    help: "Help",
    rules: "Privacy and Policy",
    logout: "Log Out",
    save: "Save",
    cancel: "Cancel",
    country: "Country:",
    region: "Region:",
    countryDefault: "What country are you in?",
    regionDefault: "What region are you in?",
    logoutModulText: "Do you want to log out?",
    errorModulText: "An error occurred! Try again.",
    enterNameError: "Enter your name!",
    enterNumberError: "Enter your phone number!",
    enterRegionError: "Enter Country and Region!",
    enterName: "Enter your name!",
  },
  blockedUsers: {
    noItem: "No blocked users",
    headerText: "Blocked users",
  },
  notifications: {
    noItem: "No notifications",
    headerText: "Notifications",
    deleteModulText: "Do you want to delete the notification?",
  },
  jobsHistory: {
    headerText: "Jobs history",
    noItemWorked: "No work history",
    noItemAdded: "No added jobs history",
    navWorked: "Worked",
    navAdded: "Added",
  },
  homesHistory: {
    noItem: "No history of ads for house rent",
    headerText: "Home rental history",
  },
  changeLanguage: {
    headerText: "Change language",
  },
  sidebar: {
    jobs: "Job ads",
    homes: "Ads for rent",
    add: "Add new",
    chat: "Messages",
    profile: "Profile",
    notifications: "Notifications",
    jobsHistory: "Jobs history",
    homesHistory: "Home rental history",
    theme: "Dark mode",
  },
  confirm: {
    successModulBtn: "Exit",
    headerText: "Confirm your email!",
    infoText:
      "To receive a confirmation message, click the send button and confirm by entering your email! (If you can't find the email, check your Spam section!)",
    sendBtn: "Send",
    retryBtn: "Re-registration",
    errorModulText: "An error occurred! Try again.",
    successModulText: "A confirmation message has been sent to your email!",
  },
  signIn: {
    headerText: "Log in",
    headerInfo: "Enter your Email and Password to login!",
    email: "Enter your email!",
    password: "Enter your password!",
    enterBtn: "Enter",
    question: "Not registered yet?",
    navigateBtn: "Sign up",
    errorEmail: "Enter your email!",
    errorEmailConfirm: "Enter your email correctly!",
    errorPassword: "Enter your password!",
    errorPasswordConfirm: "Password must be at least 6 characters long!",
    emailNoError: "Your email is not in the system! Try again!",
    errorText: "An error occurred! Try again!",
  },
  signUp: {
    headerText: "Sign up",
    headerInfo:
      "You must register to use the full features of the application!",
    googleBtn: "Sign up with Google",
    emailBtn: "Sign up with Email",
    errorModulText: "An error occurred! Try again!",
  },
  signUpWithEmail: {
    headerText: "Sign up with Email",
    name: "Enter your name!",
    email: "Enter your email!",
    password: "Enter a password!",
    rePassword: "Enter the password again!",
    submitBtn: "Sign up",
    question: "Already have an account?",
    navigateBtn: "Log in",
    imageError: "Please add a picture!",
    nameError: "Enter your name!",
    emailError: "Enter your email!",
    emailFailedError: "Enter your email correctly!",
    passwordError: "Enter a password!",
    passwordFailedError: "Password must be at least 6 characters long!",
    passwordWrongError: "Enter your password correctly!",
    emailExistsError: "Email is already registered!",
    errorText: "An error occurred! Try again!",
  },
  allNotifications: {
    successJob: "Your ad has been completed successfully!",
    deletedHome:
      "This ad has been removed because it's been 30 days since you posted it!",
    successNotification: "You have successfully completed the work!",
    deleteNotification:
      "User! The job you received has been deleted by the advertiser!",
    unbanNotification:
      "You have been removed from ban for this job by the employer!",
    removeNotification:
      "User! You have been removed from this job by the employer!",
    banNotification:
      "User! You have been banned from the current job by the employer! You cannot get this job again!",
  },
  actionModul: {
    exitBtn: "Cancel",
    noBtn: "NO",
    yesBtn: "YES",
  },
  exitHeader: {
    deleteModulText: "Do you want to delete all notifications?",
    iconInfo: "Settings",
    deleteAllText: "delete all",
    shareText: "Share",
  },
  header: {
    iconInfo: "Settings",
    blockedUsersText: "blocked users",
  },
  loadingModul: {
    text: "Loading...",
  },
  privacyAndPolicy: {
    headerText: "Privacy and policy",
  },
};

export const ru = {
  type: "ru",
  jobs: {
    noItem: "Нет работы",
    deleted: "Удалено!",
    workedWith: "человека работало",
    headerText: "Информация о работе",
    salary: "Зарплата:",
    numOfWorkers: "Количество работников:",
    phone: "Телефон:",
    copy: "Копировать",
    copied: "Скопировано!",
    time: "Время:",
    country: "Страна:",
    region: "Область, край:",
    metro: "Метро:",
    address: "Адрес:",
    comment: "Комментарий:",
    workers: "РАБОЧИЕ",
    banned: "ЗАПРЕЩЕННОЕ",
    deleteJob: "Удалить",
    cancelJob: "Отмена",
    getJob: "Получить работу",
    removeUser: "Удалить",
    unbanUser: "Разблокировать",
    modulTextDelete: "Удалить это объявление?",
    modulTextExit: "Вы хотите отменить работу?",
    modulTextGet: "Вы хотите получить работу?",
    banErrorModulText: "Работодатель забанил вас!",
    banErrorModulBtn: "Выход",
    unbanModul: "Вы хотите разбанить пользователя?",
    modulRemoveBtn: "удалить",
    modulBanBtn: "Запрет",
    modulCancelBtn: "Отмена",
  },
  homes: {
    noItem: "Объявлений об аренде нет",
    deleteModul: "Вы хотите удалить это объявление?",
    deleteBtn: "удалить",
  },
  add: {
    addJobText: "Разместить новую вакансию",
    addFree: "размещение абсолютно бесплатно",
    addHomeText: "Разместить объявление о сдаче жилья",
    myJobAdds: "Мои объявления о работе",
    myHomeAdds: "Мои объявления по аренде",
  },
  addNewJob: {
    headerText: "Заполните объявление",
    jobName: "Введите должность...",
    numOfWorkers: "Сколько рабочих нужно?...",
    address: "Введите рабочий адрес...",
    comment: "Оставить отзыв о вакансии...",
    startingTime: "Время начала",
    endingTime: "Время окончания",
    country: "Страна:",
    region: "Область:",
    countryDefault: "В какой ты стране?",
    regionDefault: "Вы в каком регионе?",
    line: "Линия:",
    station: "Станция:",
    saveBtn: "СОХРАНИТЬ",
    errorModulBtn: "Выход",
    errorModulBtnJob: "Посмотреть работу",
    errorModulText: "Вы можете размещать только 4 в день!",
    errorModulTextJob:
      "У тебя уже есть работа! Вы должны отменить работу, чтобы опубликовать!",
    jobNameError: "Введите должность!",
    salaryError: "Введите размер зарплаты!",
    workersCountError: "Введите количество сотрудников!",
    workingPlaceError: "Введите рабочий адрес!",
    commentError: "Введите комментарий!",
    startingTimeError: "Установите правильное время начала!",
    endingTimeError: "Установите правильное время окончания!",
    regionError: "Введите Страну и Регион!",
    metroError: "Введите метро рядом с работой!",
    numberError: "Введите свой номер телефона!",
  },
  addNewHome: {
    headerText: "Заполните объявление",
    rent: "Введите сумму ежемесячного платежа...",
    address: "Введите домашний адрес...",
    comment: "Оставить комментарий...",
    country: "Страна:",
    region: "Область:",
    countryDefault: "В какой ты стране?",
    regionDefault: "Вы в каком регионе?",
    line: "Линия:",
    station: "Станция:",
    saveBtn: "СОХРАНИТЬ",
    errorModulBtn: "Выход",
    errorModulText: "Вы можете размещать только 4 в день!",
    imageError: "Пожалуйста, добавьте картинку!",
    rentError: "Введите сумму ежемесячного платежа!",
    addressError: "Введите домашний адрес!",
    commentError: "Введите комментарий!",
    regionError: "Введите Страну и Регион!",
    metroError: "Введите метро рядом с домом!",
    numberError: "Введите свой номер телефона!",
  },
  chats: {
    noItem: "Нет сообщений",
    modulTextSelected: "Вы хотите удалить выбранные сообщения?",
    modulTextDelete: "Вы хотите удалить все сообщения?",
    modulTextBlock: "Вы хотите заблокировать этого пользователя?",
    modulTextUnblock: "Вы хотите разблокировать пользователя?",
    iconInfo: "Настройки",
    chooseText: "выбрать",
    deleteAllText: "удалить все",
    unblockText: "разблокировать",
    blockText: "блокировать",
    newMessagesText: "Новые сообщения",
  },
  profile: {
    phone: "Ваш номер телефона",
    gaveJobs: "люди, которых вы наняли",
    addedHomeAds: "дома в аренду вы рекламировали",
    addedJobAds: "добавленные вами вакансии",
    takenJobs: "работа, которую вы получили",
    settings: "Настройки",
    theme: "Темный Режим",
    jobsHistory: "История Вакансий",
    homesHistory: "История Аренды Дома",
    changeLanguage: "Изменить Язык",
    help: "Помощь",
    rules: "Конфиденциальность и Политика",
    logout: "Выйти",
    save: "Сохранить",
    cancel: "Отмена",
    country: "Страна:",
    region: "Область:",
    countryDefault: "В какой ты стране?",
    regionDefault: "Вы в каком регионе?",
    logoutModulText: "Выйти?",
    errorModulText: "Произошла ошибка! Попробуйте еще раз.",
    enterNameError: "Введите ваше имя!",
    enterNumberError: "Введите свой номер телефона!",
    enterRegionError: "Введите Страну и Регион!",
    enterName: "Введите ваше имя!",
  },
  blockedUsers: {
    noItem: "Нет заблокированных пользователей",
    headerText: "Заблокированные пользователи",
  },
  notifications: {
    noItem: "Нет уведомлений",
    headerText: "Уведомления",
    deleteModulText: "Вы хотите удалить уведомление?",
  },
  jobsHistory: {
    headerText: "История вакансий",
    noItemWorked: "Нет история работы",
    noItemAdded: "Нет добавленной истории вакансий",
    navWorked: "Работал",
    navAdded: "Добавлен",
  },
  homesHistory: {
    noItem: "Нет истории объявлений об аренде дома",
    headerText: "История аренды дома",
  },
  changeLanguage: {
    headerText: "Изменение языка",
  },
  sidebar: {
    jobs: "Объявления о работе",
    homes: "Объявления об аренде",
    add: "Добавить новое",
    chat: "Сообщения",
    profile: "Профиль",
    notifications: "Уведомления",
    jobsHistory: "История вакансий",
    homesHistory: "История аренды дома",
    theme: "Темный режим",
  },
  confirm: {
    successModulBtn: "Выход",
    headerText: "Подтвердите ваш адрес электронной почты!",
    infoText:
      "Чтобы получить подтверждающее сообщение, нажмите кнопку «Отправить» и подтвердите, введя свой адрес электронной почты! (Если вы не можете найти письмо, проверьте раздел «Спам»!)",
    sendBtn: "Отправить",
    retryBtn: "Перерегистрация",
    errorModulText: "Произошла ошибка! Попробуйте еще раз.",
    successModulText:
      "На вашу электронную почту отправлено письмо с подтверждением!",
  },
  signIn: {
    headerText: "Войти",
    headerInfo: "Введите адрес электронной почты и пароль для входа!",
    email: "Введите адрес электронной почты!",
    password: "Введите свой пароль!",
    enterBtn: "Войти",
    question: "Еще не зарегистрированы?",
    navigateBtn: "зарегистрироваться",
    errorEmail: "Введите адрес электронной почты!",
    errorEmailConfirm: "Введите адрес электронной почты правильно!",
    errorPassword: "Введите свой пароль!",
    errorPasswordConfirm: "Пароль должен содержать не менее 6 символов!",
    emailNoError:
      "Ваша электронная почта отсутствует в системе! Попробуйте еще раз!",
    errorText: "Произошла ошибка! Попробуйте еще раз!",
  },
  signUp: {
    headerText: "Зарегистрироваться",
    headerInfo:
      "Вы должны зарегистрироваться, чтобы использовать все возможности приложения!",
    googleBtn: "Зарегистрируйтесь c Google",
    emailBtn: "Зарегистрируйтесь c Email",
    errorModulText: "Произошла ошибка! Попробуйте еще раз!",
  },
  signUpWithEmail: {
    headerText: "Зарегистрируйтесь c Email",
    name: "Введите ваше имя!",
    email: "Введите адрес электронной почты!",
    password: "Введите пароль!",
    rePassword: "Введите пароль еще раз!",
    submitBtn: "Зарегистрироваться",
    question: "У вас уже есть аккаунт?",
    navigateBtn: "Войти",
    imageError: "Пожалуйста, добавьте картинку!",
    nameError: "Введите ваше имя!",
    emailError: "Введите адрес электронной почты!",
    emailFailedError: "Введите адрес электронной почты правильно!",
    passwordError: "Введите пароль!",
    passwordFailedError: "Пароль должен содержать не менее 6 символов!",
    passwordWrongError: "Введите пароль правильно!",
    emailExistsError: "Электронная почта уже зарегистрирована!",
    errorText: "Произошла ошибка! Попробуйте еще раз!",
  },
  allNotifications: {
    successJob: "Ваше объявление успешно завершено!",
    deletedHome:
      "Это объявление было удалено, так как с момента его размещения прошло 30 дней!",
    successNotification: "Вы успешно завершили работу!",
    deleteNotification:
      "Пользователь! Полученная вами вакансия удалена рекламодателем!",
    unbanNotification: "Вы сняты с бана на эту вакансию работодателем!",
    removeNotification:
      "Пользователь! Вы были сняты с этой работы работодателем!",
    banNotification:
      "Пользователь! Вы были отстранены от текущей работы работодателем! Вы не можете получить эту работу снова!",
  },
  actionModul: {
    exitBtn: "Отмена",
    noBtn: "НЕТ",
    yesBtn: "ДА",
  },
  exitHeader: {
    deleteModulText: "Удалить все уведомления?",
    iconInfo: "Настройки",
    deleteAllText: "удалить все",
    shareText: "Поделиться",
  },
  header: {
    iconInfo: "Настройки",
    blockedUsersText: "Заблокированные пользователи",
  },
  loadingModul: {
    text: "Загрузка...",
  },
  privacyAndPolicy: {
    headerText: "Конфиденциальность и политика",
  },
};

export const uz = {
  type: "uz",
  jobs: {
    noItem: "Xozircha ish uchun e'lonlar yo'q",
    deleted: "O'chirilgan!",
    workedWith: "ta odamga ish bergan",
    headerText: "Ish haqida malumotlar",
    salary: "Ish xaqqi:",
    numOfWorkers: "Ishchilar soni:",
    phone: "Telefon:",
    copy: "Nusxalash",
    copied: "Nusxalandi!",
    time: "Ish vaqti:",
    country: "Davlat:",
    region: "Region:",
    metro: "Metro:",
    address: "Manzil:",
    comment: "Kommentariya:",
    workers: "ISHCHILAR",
    banned: "BAN QILINGANLAR",
    deleteJob: "Elonni o'chirish",
    cancelJob: "Bekor qilish",
    getJob: "Ishni olish",
    removeUser: "Chiqarish",
    unbanUser: "Bandan olish",
    modulTextDelete: "E'lonni o'chirishni xoxlaysizmi?",
    modulTextExit: "Ishni bekor qilishni xoxlaysizmi?",
    modulTextGet: "Ishni olishni xoxlaysizmi?",
    banErrorModulText: "Ish beruvchi sizni ban qilgan!",
    banErrorModulBtn: "Chiqish",
    unbanModul: "Foydalanuvchini bandan chiqarishni xoxlaysizmi?",
    modulRemoveBtn: "Ro'yxatdan chiqarish",
    modulBanBtn: "Ban qilish",
    modulCancelBtn: "Bekor qilish",
  },
  homes: {
    noItem: "Xozircha uy ijarasi uchun e'lonlar yo'q",
    deleteModul: "E'lonni o'chirishni xoxlaysizmi?",
    deleteBtn: "o'chirish",
  },
  add: {
    addJobText: "Ish berish uchun e'lon qo'shish",
    addFree: "e'lon berish mutlaqo bepul",
    addHomeText: "Uy ijaraga berish uchun e'lon qo'shish",
    myJobAdds: "Ish uchun e'lonlarim",
    myHomeAdds: "Uy ijarasi uchun e'lonlarim",
  },
  addNewJob: {
    headerText: "E'lonni to'ldiring",
    jobName: "Ish nomini kiriting...",
    numOfWorkers: "Nechta ishchi kerak?...",
    address: "Ishlash manzilini kiriting...",
    comment: "Ish haqida kommentariya qoldiring...",
    startingTime: "Ish boshlanish vaqti",
    endingTime: "Ish tugash vaqti",
    country: "Davlat:",
    region: "Region:",
    countryDefault: "Qaysi davlatdasiz?",
    regionDefault: "Qaysi regiondasiz?",
    line: "Liniya:",
    station: "Stansiya:",
    saveBtn: "SAQLASH",
    errorModulBtn: "Chiqish",
    errorModulBtnJob: "Ishni ko'rish",
    errorModulText: "Kuniga faqat 4ta e'lon berishingiz mumkin!",
    errorModulTextJob:
      "Allaqachon ish olgansiz! E'lon berish uchun ishni bekor qilishingiz kerak!",
    jobNameError: "Ish nomini kiriting!",
    salaryError: "Ish xaqqi miqdorini kiriting!",
    workersCountError: "Ishchilar sonini kiriting!",
    workingPlaceError: "Ishlash manzilini kiriting!",
    commentError: "Kommentariya kiriting!",
    startingTimeError: "Ish boshlanish vaqtini to'g'ri belgilang!",
    endingTimeError: "Ish tugash vaqtini to'g'ri belgilang!",
    regionError: "Davlat va Regionni kiriting!",
    metroError: "Ish joyiga yaqin metroni kiriting!",
    numberError: "Telefon raqamingizni kiriting!",
  },
  addNewHome: {
    headerText: "E'lonni to'ldiring",
    rent: "Oylik to'lov narxini kiriting...",
    address: "Uy manzilini kiriting...",
    comment: "Kommentariya qoldiring...",
    country: "Davlat:",
    region: "Region:",
    countryDefault: "Qaysi davlatdasiz?",
    regionDefault: "Qaysi regiondasiz?",
    line: "Liniya:",
    station: "Stansiya:",
    saveBtn: "SAQLASH",
    errorModulBtn: "Chiqish",
    errorModulText: "Kuniga faqat 4ta e'lon berishingiz mumkin!",
    imageError: "Iltimos rasm joylang!",
    rentError: "Oylik to'lov narxini kiriting!",
    addressError: "Uy manzilini kiriting!",
    commentError: "Kommentariya kiriting!",
    regionError: "Davlat va Regionni kiriting!",
    metroError: "Uyga yaqin metroni kiriting!",
    numberError: "Telefon raqamingizni kiriting!",
  },
  chats: {
    noItem: "Xozircha xabarlar yo'q",
    modulTextSelected: "Tanlangan xabarlarni o'chirishni xoxlaysizmi?",
    modulTextDelete: "Barcha xabarlarni o'chirishni xoxlaysizmi?",
    modulTextBlock: "Foydalanuvchini bloklashni xoxlaysizmi?",
    modulTextUnblock: "Foydalanuvchini blokdan chiqarishni xoxlaysizmi?",
    iconInfo: "Sozlamalar",
    chooseText: "tanlash",
    deleteAllText: "hammasini o'chirish",
    unblockText: "blokdan chiqarish",
    blockText: "bloklash",
    newMessagesText: "Yangi xabarlar",
  },
  profile: {
    phone: "Telefon raqamingiz",
    gaveJobs: "ta odamni ish bilan ta'minlagansiz",
    addedHomeAds: "ta uy ijarasi uchun e'lon bergansiz",
    addedJobAds: "ta ish uchun e'lon bergansiz",
    takenJobs: "ta ish olgansiz",
    settings: "Sozlamalar",
    theme: "Ilova Ranggi",
    jobsHistory: "Ishlar Tarixi",
    homesHistory: "Uy Ijaralari Tarixi",
    changeLanguage: "Tilni O'zgartirish",
    help: "Yordam",
    rules: "Ilova Qoidalari",
    logout: "Tizimdan Chiqish",
    save: "Saqlash",
    cancel: "Qaytish",
    country: "Davlat:",
    region: "Region:",
    countryDefault: "Qaysi davlatdasiz?",
    regionDefault: "Qaysi regiondasiz?",
    logoutModulText: "Tizimdan chiqishni xoxlaysizmi?",
    errorModulText: "Xatolik yuz berdi! Qayta urinib ko'ring.",
    enterNameError: "Ismingizni kiriting!",
    enterNumberError: "Telefon raqamingizni kiriting!",
    enterRegionError: "Davlat va Regionni kiriting!",
    enterName: "Ismingizni kiriting!",
  },
  blockedUsers: {
    noItem: "Bloklangan foydalanuvchilar yo'q",
    headerText: "Bloklangan foydalanuvchilar",
  },
  notifications: {
    noItem: "Bildirishnomalar yo'q",
    headerText: "Bildirishnomalar",
    deleteModulText: "Bildirishnomani o'chirishni xoxlaysizmi?",
  },
  jobsHistory: {
    headerText: "Ishlar tarixi",
    noItemWorked: "Olingan ishlar tarixi yo'q",
    noItemAdded: "Berilgan e'lonlar tarixi yo'q",
    navWorked: "Ishlaganlarim",
    navAdded: "Bergan e'lonlarim",
  },
  homesHistory: {
    noItem: "Uy ijarasi uchun e'lonlar tarixi yo'q",
    headerText: "Uy ijaralari tarixi",
  },
  changeLanguage: {
    headerText: "Tilni o'zgartirish",
  },
  sidebar: {
    jobs: "Ish uchun e'lonlar",
    homes: "Uy ijarasi uchun e'lonlar",
    add: "E'lon qo'shish",
    chat: "Xabarlar",
    profile: "Foydalanuvchi",
    notifications: "Bildirishnomalar",
    jobsHistory: "Ishlar tarixi",
    homesHistory: "Uy ijaralari tarixi",
    theme: "Ilova ranggi",
  },
  confirm: {
    successModulBtn: "Chiqish",
    headerText: "Emailingizni tasdiqlang!",
    infoText:
      "Tasdiqlash xabarini olish uchun yuborish tugmasini bosing va Emailigizga kirib tasdiqlang! (Agarda Emailni topolmasangiz Spam bo'limini tekshirib ko'ring!)",
    sendBtn: "Yuborish",
    retryBtn: "Qayta ro'yxatdan o'tish",
    errorModulText: "Xatolik yuz berdi! Qayta urinib ko'ring.",
    successModulText: "Emailingizga tasdiqlash xabari yuborildi!",
  },
  signIn: {
    headerText: "Tizimga kirish",
    headerInfo: "Tizimga kirish uchun Email va Parolingizni kiriting!",
    email: "Emailingizni kiriting!",
    password: "Parolingizni kiriting!",
    enterBtn: "Kirish",
    question: "Xali ro'yxatdan o'tmaganmisiz?",
    navigateBtn: "Ro'yxatdan o'tish",
    errorEmail: "Emailingizni kiriting!",
    errorEmailConfirm: "Emailingizni to'g'ri kiriting!",
    errorPassword: "Parolingizni kiriting!",
    errorPasswordConfirm: "Parol kamida 6ta belgidan iborat bo'lishi kerak!",
    emailNoError: "Emailingiz tizimda yo'q! Qayta urinib ko'ring!",
    errorText: "Xatolik yuz berdi! Qayta urinib ko'ring!",
  },
  signUp: {
    headerText: "Ro'yxatdan o'tish",
    headerInfo:
      "Ilovaning to'liq imkoniyatlaridan foydalanish uchun ro'yxatdan o'tishingiz kerak!",
    googleBtn: "Google orqali ro'yxatdan o'tish",
    emailBtn: "Email orqali ro'yxatdan o'tish",
    errorModulText: "Xatolik yuz berdi! Qayta urinib ko'ring!",
  },
  signUpWithEmail: {
    headerText: "Email orqali ro'yxatdan o'tish",
    name: "Ismingizni kiriting!",
    email: "Emailingizni kiriting!",
    password: "Parol kiriting!",
    rePassword: "Parolni qayta kiriting!",
    submitBtn: "Ro'yxatdan o'tish",
    question: "Akkauntingiz allaqachon bormi?",
    navigateBtn: "Kirish",
    imageError: "Iltimos rasm joylang!",
    nameError: "Ismingizni kiriting!",
    emailError: "Emailingizni kiriting!",
    emailFailedError: "Emailingizni to'g'ri kiriting!",
    passwordError: "Parol kiriting!",
    passwordFailedError: "Parol kamida 6ta belgidan iborat bo'lishi kerak!",
    passwordWrongError: "Parolingizni to'g'ri kiriting!",
    emailExistsError: "Email allaqchon ro'yxatdan o'tgan!",
    errorText: "Xatolik yuz berdi! Qayta urinib ko'ring!",
  },
  allNotifications: {
    successJob: "Bergan e'loningiz muvaffaqiyat tugatildi!",
    deletedHome:
      "E'lon berganingizga 30 kun bo'lganligi sababli ushbu e'lon o'chirib tashlandi!",
    successNotification: "Ishni muvaffaqiyat tamomladingiz!",
    deleteNotification:
      "Foydalanuvchi! Siz olgan ishingiz e'lon beruvchi tomonidan o'chirib tashlandi!",
    unbanNotification:
      "Ish beruvchi tomonidan joriy ish uchun bandan chiqarildingiz!",
    removeNotification:
      "Foydalanuvchi! Siz ish beruvchi tomonidan ishdan chetlashtirildingiz!",
    banNotification:
      "Foydalanuvchi! Siz ish beruvchi tomonidan joriy ish uchun ban qilindingiz! Endi ushbu ishni qayta ololmaysiz!",
  },
  actionModul: {
    exitBtn: "Qaytish",
    noBtn: "YO'Q",
    yesBtn: "HA",
  },
  exitHeader: {
    deleteModulText: "Bildirishnomalarni o'chirishni xoxlaysizmi?",
    iconInfo: "Sozlamalar",
    deleteAllText: "hammasini o'chirish",
    shareText: "Tarqatish",
  },
  header: {
    iconInfo: "Sozlamalar",
    blockedUsersText: "bloklangan foydalanuvchilar",
  },
  loadingModul: {
    text: "Yuklanyabdi...",
  },
  privacyAndPolicy: {
    headerText: "Ilova qoidalari",
  },
};
